[versions]
agp = "8.6.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
material = "1.13.0"
appcompat = "1.7.1"
kotlin = "2.3.0"
room = "2.6.1"
[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
media3-exoplaye = { module = "androidx.media3:media3-exoplayer", version = "1.9.0" }
media3-ui = { module = "androidx.media3:media3-ui", version = "1.9.0" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.10.2" }
room-runtime = { group = "androidx.room", name = "room-runtime", version = "2.7.0" }
room-compiler = { group = "androidx.room", name = "room-compiler", version = "2.7.0" }
room-ktx = { group = "androidx.room", name = "room-ktx", version = "2.7.0" }
androidx-lifecycle-livedata-ktx= { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version = "1.10.0" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version = "1.8.9" }
lottie = { group = "com.airbnb.android", name = "lottie", version = "5.2.0" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.6.2" }
glide = { group = "com.github.bumptech.glide", name = "glide", version = "4.16.0" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version = "4.16.0" }
aria-core = { module = "me.laoyuyu.aria:core", version = "3.8.16" }
aria-compile =  { module = "me.laoyuyu.aria:compiler", version = "3.8.16" }
aria-m3u8 = { module = "me.laoyuyu.aria:m3u8", version = "3.8.16" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version = "25.0.0" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version = "34.9.0" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics"}
firebase-perf = { module = "com.google.firebase:firebase-perf"}
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics"}
facebook-android-sdk = { module = "com.facebook.android:facebook-android-sdk",version = "latest.release"}
installreferrer = { module = "com.android.installreferrer:installreferrer", version = "2.2"}
af-android-sdk = { module = "com.appsflyer:af-android-sdk", version = "6.17.5"}
multidex = { module = "androidx.multidex:multidex", version = "2.0.1" }
transformer = { module = "androidx.media3:media3-transformer", version = "1.9.0"}
exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version = "1.9.0"}
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "1.9.23"}


